version: '3.9'

services: 
    postgres-dev:
        image: postgres
        environment:
            POSTGRES_PASSWORD: pass123
            POSTGRES_DB: q2pay-dev
        ports: 
            - 5432:5432
