version: '3.9'

services: 
    api:
        image: q2pay-api
        build: .
        ports:
            - 8080:8080
        environment:
            - DB_DEV_HOST=postgres
        depends_on:
            postgres:
                condition: service_healthy
        command: bash -c "app --migrate && app"

    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: supersecret
            POSTGRES_DB: q2pay-dev
        ports: 
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d q2pay-dev"]
            interval: 10s
            timeout: 5s
            retries: 5
